### ISSUE TITLE
Job is failing without clear error message.

### ISSUE THREAD

**Issue by soichih** [brain-life/app-mrtrix3-preproc#1]
When I run this App, it fails without displaying a clear error message.

I see a lot of output files after several hours of execution.

![screenshot from 2018-06-01 13-37-11](https://user-images.githubusercontent.com/923896/40854906-e65ac4e6-65a0-11e8-9916-e35b0d02fbb1.png)

summary.txt contains

```
single-shell: 1 total shell
Number of b0s: 10

shell / count / lmax
0 2000 
10 96 
2 12
```

Here is the bottom of the slurm log

```
0.323120 0.999992 0.003854 -0.000476 0.000000 -0.003853 0.999989 0.002685 0.000000 0.000486 -0.002683 0.999996 0.000000 0.567343 0.323797 0.290358 1.000000 
VAL: 1p5
Creating acpc space b0 reference images...
dwi_denoise_eddy_bias_norm_acpc_1p5mm.mif FOUND
Creating preprocessed dwi files in acpc space...
Writing text file of basic sequence information...
single-shell: 1 total shell
Number of b0s: 10

shell / count / lmax
0 2000 
10 96 
2 12
Cleaning up working directory...
Final dwi data files are missing.
```

bottom of the err log

```
[33mWARNING: Warning reading tar header: Ignoring malformed pax extended attribute
[0m[33mWARNING: Warning reading tar header: Ignoring malformed pax extended attribute
[0mdwipreproc: [00;31m[WARNING] CUDA version of eddy not found; running standard version[0m
dwipreproc: [00;31m[WARNING] Total readout time not provided at command-line; assuming sane default of 0.1[0m

real	236m7.674s
user	264m2.808s
sys	6m7.477s
```

**Comment by bcmcpher** [comment]
I think this is working, but the check for the final output file is wrong
so it is saying it fails. The final files look like they're there and not
empty (dwi_denoise_eddy_bias_norm_acpc_1p5mm.*).

This still needs to be fixed to have the openMP / CUDA versions in the
docker container (and run on a CUDA enabled machine, ideally), but it looks
to be working.

Do I have access to this output? I can check that the outputs aren't junk
and figure out what is wrong with the file check.

Brent

**Comment by soichih** [comment]
@bcmcpher You should have access to my test project. Here is the process
> https://brainlife.io/project/5a74ccd66ed91402ce400cc6/process/5b1149e7be003b0049a12670

So you are creating symlinks inside ./out directory to organize the final output files. I just checked, and they all pointing to a wrong paths.

```
rlife@slurm1:/mnt/share1/prod/5b1149e7be003b0049a12670/5b1149e7be003b0049a12673/out$ ls -la
total 8
drwxr-xr-x 2 brlife brlife 4096 Jun  1 17:24 .
drwxrwxr-x 4 brlife brlife 4096 Jun  1 17:24 ..
lrwxrwxrwx 1 brlife brlife   27 Jun  1 17:24 anat_acpc_brain_mask.nii.gz -> anat_acpc_brain_mask.nii.gz
lrwxrwxrwx 1 brlife brlife   22 Jun  1 17:24 anat_acpc_brain.nii.gz -> anat_acpc_brain.nii.gz
lrwxrwxrwx 1 brlife brlife   16 Jun  1 17:24 anat_acpc.nii.gz -> anat_acpc.nii.gz
lrwxrwxrwx 1 brlife brlife   25 Jun  1 17:24 b0_acpc_brain_mask.nii.gz -> b0_acpc_brain_mask.nii.gz
lrwxrwxrwx 1 brlife brlife   20 Jun  1 17:24 b0_acpc_brain.nii.gz -> b0_acpc_brain.nii.gz
lrwxrwxrwx 1 brlife brlife   14 Jun  1 17:24 b0_acpc.nii.gz -> b0_acpc.nii.gz
lrwxrwxrwx 1 brlife brlife   24 Jun  1 17:24 b0_dwi_brain_mask.nii.gz -> b0_dwi_brain_mask.nii.gz
lrwxrwxrwx 1 brlife brlife   19 Jun  1 17:24 b0_dwi_brain.nii.gz -> b0_dwi_brain.nii.gz
lrwxrwxrwx 1 brlife brlife   13 Jun  1 17:24 b0_dwi.nii.gz -> b0_dwi.nii.gz
lrwxrwxrwx 1 brlife brlife   43 Jun  1 17:24 dwi.bvals -> dwi_denoise_eddy_bias_norm_acpc_1p5mm.bvals
lrwxrwxrwx 1 brlife brlife   43 Jun  1 17:24 dwi.bvecs -> dwi_denoise_eddy_bias_norm_acpc_1p5mm.bvecs
lrwxrwxrwx 1 brlife brlife   44 Jun  1 17:24 dwi.nii.gz -> dwi_denoise_eddy_bias_norm_acpc_1p5mm.nii.gz
```

For example, dwi.nii.gz should point to 
`../dwi_denoise_eddy_bias_norm_acpc_1p5mm.nii.gz`
not
`dwi_denoise_eddy_bias_norm_acpc_1p5mm.nii.gz`

If you fix this, I think the existing check on `main` script should work. Or.. since you are running a bash script, you can actually output a proper exit code and test it on `main` also.

**Comment by soichih** [comment]
I believe this has been fixed already.
