### ISSUE TITLE
eddy_opemmp high cpu usage

### ISSUE THREAD

**Issue by soichih** [brain-life/app-mrtrix3-preproc#10]
This App currently requests for 8 CPU cores, but during the execution, CPU usage exceed beyond requested amount of CPU. 

![Screenshot from 2019-10-04 13-56-50](https://user-images.githubusercontent.com/923896/66229033-f031bc00-e6ae-11e9-9049-852a02baccb9.png)

It looks like eddy_opemmp is the process that using high CPU. This could be dwipreproc issue.

**Comment by bcmcpher** [comment]
What's the problem exactly? Is it taking cores beyond it's allotment? If it
is it's a dwipreproc issue b/c eddy_openmp isn't following the passed core
argument.

What resource is this happening on - could be something with how it is
configured to run jobs? I can't imagine we've run as much data as we have
without realizing this is going on.

**Comment by soichih** [comment]
Most batch schedulers are pretty lenient about exceeding CPU cores, so I don't think this has been an issue, but it *could* lock up the node if too many misbehaving jobs land on the same node.. (or killed by the scheduler)

I will ping this thread and see what they say 
> https://github.com/MRtrix3/mrtrix3/issues/1479

**Comment by soichih** [comment]
I've added export for OMP_NUM_THREADS to work around the mrtrix3 side issue. I haven't tested it, and the change only exists on master

**Comment by soichih** [comment]
I am no longer seeing this problem. I believe the update we made fixed it.
